stages:
  - test
  - lint

.only-default: &only-default
  only:
    - merge_requests
    - tags
    - branches
    - pushes
    - web

  # docker image
image: ubuntu:20.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# run tests using the binary built before
test:
  stage: test
  <<: *only-default
  before_script:
    - apt update && DEBIAN_FRONTEND=noninteractive apt-get install -yq python3.8 python3-venv git
    - git submodule update --init --recursive
    - python3.8 -m venv venv
  script:
    - source venv/bin/activate
    - pip install wheel
    - pip install -r requirements.txt
    - python -m pytest --cov --cov-report xml
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml

lint:
  stage: lint
  only:
    - merge_requests
  before_script:
    - apt update && DEBIAN_FRONTEND=noninteractive apt-get install -yq python3.8 python3-venv git
    - git submodule update --init --recursive
    - python3.8 -m venv venv
  script:
    - source venv/bin/activate
    - pip install wheel pylint
    - pylint src test
